services:
    activemq:
      image: islandora/activemq:main@sha256:167f8ad44e0489be36b912d33f0eab7a2ee87ab137385c85a48f8bc1cc02e222
      ports:
        - "8161:8161"
    isle-event-bus:
      image: libops/isle-event-bus:main
      depends_on:
        activemq:
          condition: service_healthy
    file-server:
      image: fs:main
      volumes:
        - ./fixtures:/tmp:rw
    test:
      image: alpine@sha256:a8560b36e8b8210634f77d9f7f9efd7ffa463e380b75e2e74aff4511df3ef88c
      command: tail -f /dev/null
      volumes:
        - ./test.sh:/test.sh
        - ./fixtures:/tmp:r
      depends_on:
        isle-event-bus:
          condition: service_started
